apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql-container
    image: 976199020745.dkr.ecr.us-east-1.amazonaws.com/clo835_assigment2:mysql_v1.0
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: tanatip1234