apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-container
        image: 976199020745.dkr.ecr.us-east-1.amazonaws.com/clo835_assigment2:myapp_v1.0
        env:
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: "mysqlservice.db.svc.cluster.local"
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: "tanatip1234"
        ports:
        - containerPort: 8080
